  DW_SR_map_refactor[m
  SR_DW_170_chloropleth_map[m
  SR_DW_171_monthly_chart[m
  SR_DW_171_monthly_table[m
* [32mdevelop[m
  dw_175_expand_prototype[m
  dw_175_expand_table[m
  dw_add_table_components[m
  dw_card_refactor[m
  dw_implement_map[m
  dw_modal_infrastructure[m
  dw_quick_maps_header[m
  dw_sr_africa_chloropleth[m
  dw_sr_chart[m
  dw_sr_quickmaps_framework[m
  dw_sr_quickmaps_retructure[m
  jyou-baseline-scaffold[m
  main[m
  sr_chart[m
