export class ProjectedAvailability {
  private constructor(
    public readonly country: string,
    public readonly year: number,
    public readonly scenario: string,
    public readonly Ca: number,
    public readonly CaDiff: number,
    public readonly B9: number,
    public readonly B9Diff: number,
    public readonly Fe: number,
    public readonly FeDiff: any,
    public readonly B3: number,
    public readonly B3Diff: number,
    public readonly P: number,
    public readonly PDiff: number,
    public readonly K: number,
    public readonly KDiff: number,
    public readonly Protein: number,
    public readonly ProteinDIff: number,
    public readonly B2: number,
    public readonly B2Diff: number,
    public readonly B1: number,
    public readonly B1Diff: number,
    public readonly A: number,
    public readonly ADiff: number,
    public readonly B6: number,
    public readonly B6Diff: number,
    public readonly C: number,
    public readonly CDiff: number,
    public readonly Zn: number,
    public readonly ZnDiff: number,
  ) { }

  public static makeFromObject(country: string, year: number, obj: Record<string, unknown>): ProjectedAvailability {
    return new ProjectedAvailability(
      country,
      year,
      obj.scenario as string,
      obj.Ca as number,
      obj.CaDiff as number,
      obj.B9 as number,
      obj.B9Diff as number,
      obj.Fe as number,
      obj.FeDiff as number,
      obj.B3 as number,
      obj.B3Diff as number,
      obj.P as number,
      obj.PDiff as number,
      obj.K as number,
      obj.KDiff as number,
      obj.Protein as number,
      obj.ProteinDIff as number,
      obj.B2 as number,
      obj.B2Diff as number,
      obj.B1 as number,
      obj.B1Diff as number,
      obj.A as number,
      obj.ADiff as number,
      obj.B6 as number,
      obj.B6Diff as number,
      obj.C as number,
      obj.CDiff as number,
      obj.Zn as number,
      obj.ZnDiff as number,
    );
  }
}
