export class projectedAvailability {
  private constructor(
    public readonly country: string,
    public readonly year: number,
    public readonly scenario: string,
    public readonly Ca: string,
    public readonly CaDiff: string,
    public readonly B9: string,
    public readonly B9Diff: string,
    public readonly Fe: string,
    public readonly FeDiff: any,
    public readonly B3: string,
    public readonly B3Diff: string,
    public readonly P: string,
    public readonly PDiff: string,
    public readonly K: string,
    public readonly KDiff: string,
    public readonly Protein: string,
    public readonly ProteinDIff: string,
    public readonly B2: string,
    public readonly B2Diff: string,
    public readonly B1: string,
    public readonly B1Diff: string,
    public readonly A: string,
    public readonly ADiff: string,
    public readonly B6: string,
    public readonly B6Diff: string,
    public readonly C: string,
    public readonly CDiff: string,
    public readonly Zn: string,
    public readonly ZnDiff: string,
  ) {}

  public static makeFromObject(country: string, year: number, obj: Record<string, unknown>): projectedAvailability {
    return new projectedAvailability(
      country,
      year,
      obj.scenario as string,
      obj.Ca as string,
      obj.CaDiff as string,
      obj.B9 as string,
      obj.B9Diff as string,
      obj.Fe as string,
      obj.FeDiff as string,
      obj.B3 as string,
      obj.B3Diff as string,
      obj.P as string,
      obj.PDiff as string,
      obj.K as string,
      obj.KDiff as string,
      obj.Protein as string,
      obj.ProteinDIff as string,
      obj.B2 as string,
      obj.B2Diff as string,
      obj.B1 as string,
      obj.B1Diff as string,
      obj.A as string,
      obj.ADiff as string,
      obj.B6 as string,
      obj.B6Diff as string,
      obj.C as string,
      obj.CDiff as string,
      obj.Zn as string,
      obj.ZnDiff as string,
    );
  }
}
