name: Analyse Bundle
on: pull_request_target
jobs:
  build-head:
    name: "Build Current Branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:stats
      - name: Upload stats.json
        uses: actions/upload-artifact@v2.2.4
        with:
          name: head-stats
          path: ./dist/micronutrient-support-tool/stats.json

  build-base:
    name: "Build Develop Branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.base_ref }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:stats
      - name: Upload stats.json
        uses: actions/upload-artifact@v2.2.4
        with:
          name: base-stats
          path: ./dist/micronutrient-support-tool/stats.json

  compare:
    name: "Compare base & head bundle sizes"
    runs-on: ubuntu-latest
    needs: [build-base, build-head]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Download base artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: base-stats
          path: base-stats
      - name: Download head artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: head-stats
          path: head-stats
      - name: Diff between base & head
        uses: micronutrientsupport/webpack-stats-diff-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base_stats_path: ./base-stats/stats.json
          head_stats_path: ./head-stats/stats.json
          document_extensions: "html"
          script_extensions: "js,jsx,ts,tsx"
          stylesheet_extensions: "css"
          image_extensions: "jpg,jpeg,png,svg,ico,webp"
          misc_extensions: "json,geojson,yml,yaml"
