name: Verify pull request commitlint
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm install --immutable --immutable-cache --check-cache

      - name: Lint pull request title
        uses: JulienKode/pull-request-name-linter-action@v0.5.0
        with:
          configuration-path: ./commitlint.config.js
