name: Compodoc
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v3

      - name: Build compodoc
        run: |
          ls -alh
          npx @compodoc/compodoc@1.1.15 -p ./tsconfig.json
      - name: Deploy docs to netlify
        id: deploy-netlify
        if: github.event_name == 'pull_request'
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          PR: docs${{ github.event.number }}
        with:
          args: deploy --dir=documentation --alias ${PR}

      - name: Compodoc Preview URL
        uses: unsplash/comment-on-pr@master
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: "The compodoc for this PR is being automatically deployed to Netlify.\n\n🔍 Deploy log: ${{ steps.deploy-netlify.outputs.NETLIFY_LOGS_URL }}\n📖  Compodoc: ${{ steps.deploy-netlify.outputs.NETLIFY_URL }}"
        with:
          msg: ${{ env.OUTPUT }}
          check_for_duplicate_msg: false
