name: Compodoc
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Build compodoc
        run: |
          ls -alh
          npx compodoc -p ./tsconfig.json

      - name: Deploy docs to netlify
        id: deploy-netlify
        if: github.event_name == 'pull_request'
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          PR: docs${{ github.event.number }}
        with:
          args: deploy --dir=documentation --alias ${PR}