name: Auto rebase open Dependabot PRs
on:
  push:
  release:
    types: [published]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  auto-rebase:
    name: rebase dependabot PRs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.event == 'release'
    timeout-minutes: 5
    steps:
      - name: rebase
        uses: "bbeesley/gha-auto-dependabot-rebase@main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
