name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cypress run
        uses: cypress-io/github-action@v2.9.1
        with:
          # build: npm run build
          start: npm start --configuration=production
          wait-on: http://localhost:8100
