name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 10 copies of the current job in parallel
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cypress run
        uses: cypress-io/github-action@v2.9.12
        with:
          # build: npm run build
          start: npm run start-prod
          # config: requestTimeout=41000
          wait-on: http://localhost:8100
          # 120 //secs
          wait-on-timeout: 120
