name: Cypress Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Cypress run
        uses: cypress-io/github-action@v3.0.2
        with:
          # build: npm run build
          start: npm run start-prod
          # config: requestTimeout=41000
          wait-on: http://localhost:8100
          # 120 //secs
          wait-on-timeout: 120

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v2.3.1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v2.3.1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
