name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          # build: npm run build
          start: npm run start-prod
          # config: requestTimeout=41000
          wait-on: http://localhost:8100
          # 120 //secs
          wait-on-timeout: 120
