name: Linting
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npx eslint . --ext .ts
